project_id = "voshjohohxwmqlmdabyg"

[functions.create-payment]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.search-products]
verify_jwt = false

[functions.cleanup-old-tickets]
verify_jwt = false

[functions.smart-search]
verify_jwt = false